= My Project
Lydia Reiter
1.0.0, 2021-10-16: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== What
=== What is this project about

My idea is the game rush hour. Rush hour is a game where you have to get your car out of a full parket place.

[%hardbreaks]

== Why
=== Why is it a good idea
A lot of children nowadays are playing with phones. This game should help them to learn to search solutions for their problems.

[%hardbreaks]

== How
=== What technologies will i use
Used Software:

* https://www.jetbrains.com/de-de/idea/[Intellij Idea]
* https://github.com/[GitHub]

Used programming language:

* https://www.java.com/[Java]
* https://openjfx.io/[JavaFX]

[%hardbreaks]

== Who
=== Who will help
On this project I will work alone. In school we will learn the using technologies so I would say that is also a way of help.

[%hardbreaks]

== When
=== When will it start
This Project will start february 2022 and will and will be developed until july 2022.

[%hardbreaks]

== Information
I will document everything I will do on this project so everyone can understand what I am doing and can develop their own version of this game.

[%hardbreaks]
[%hardbreaks]

2021-10-16
Reiter Lydia
